#!/usr/bin/env bash

USERNAME=agent
HOME=/home/agent

adduser --home $HOME --disabled-password --gecos "agent" $USERNAME

echo 'agent ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

mkdir $HOME/.ssh
chmod 755 $HOME/.ssh
chown -R $USERNAME $HOME/.ssh
